# Generated by Django 4.2.5 on 2025-02-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_genre_instrument_business_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='class_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='home_studio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musician',
            name='stage_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='years_played',
            field=models.IntegerField(null=True),
        ),
    ]
