# Generated by Django 4.2.5 on 2025-02-27 06:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_business_industry_alter_instrument_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('image_urls', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tagged_users', models.ManyToManyField(related_name='tagged_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
