# Generated by Django 5.1.6 on 2025-03-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_user_followers_follower'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.CheckConstraint(check=~models.Q(('follower', models.F('following')), _negated=True), name='prevent_self_follow'),
        ),
    ]
