# Generated by Django 5.1.6 on 2025-03-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_user_phone'),
        ('pages', '0010_follower_prevent_self_follow'),
    ]

    operations = [
    ]