# Generated by Django 5.1.6 on 2025-03-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_follower'),
        ('pages', '0010_follower_prevent_self_follow'),
    ]

    operations = [
    ]
