# Generated by Django 5.1.6 on 2025-03-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_merge_20250328_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='instruments',
        ),
        migrations.CreateModel(
            name='MusicianInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_played', models.PositiveIntegerField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.instrument')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.musician')),
            ],
            options={
                'db_table': 'pages_musicianinstrument',
                'unique_together': {('musician', 'instrument')},
            },
        ),
    ]
