# Generated by Django 4.2.20 on 2025-03-29 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_merge_20250328_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_played', models.PositiveIntegerField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.instrument')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.musician')),
            ],
            options={
                'db_table': 'pages_musicianinstrument',
                'unique_together': {('musician', 'instrument')},
            },
        ),
        migrations.RemoveField(
            model_name='musician',
            name='instruments',
        ),
        migrations.AddField(
            model_name='musician',
            name='instruments',
            field=models.ManyToManyField(through='pages.MusicianInstrument', to='pages.instrument'),
        )
    ]
