# Generated by Django 5.1.6 on 2025-03-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_musician_instruments_musicianinstrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='instruments',
            field=models.ManyToManyField(through='pages.MusicianInstrument', to='pages.instrument'),
        ),
    ]
