# Generated by Django 4.2.20 on 2025-04-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_musician_instruments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='s3_url',
        ),
    ]
