# Generated by Django 4.2.20 on 2025-04-03 03:07

from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_musician_instruments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follower',
            name='prevent_self_follow',
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.CheckConstraint(check=models.Q(('follower', models.F('following')), _negated=True), name='prevent_self_follow'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='s3_url',
        ),
    ]
