# Generated by Django 5.1.6 on 2025-04-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_post_s3_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged_users',
        ),
    ]
