# Generated by Django 4.2.20 on 2025-04-11 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_post_tagged_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(related_name='tagged_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
