# Generated by Django 5.1.7 on 2025-04-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_blockeduser'),
        ('pages', '0016_remove_post_file_key_remove_post_file_type_and_more'),
    ]

    operations = [
    ]
