# Generated by Django 5.1.7 on 2025-04-11 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_merge_20250411_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(related_name='tagged_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
