# Generated by Django 5.1.7 on 2025-04-14 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ban_admin',
            field=models.ManyToManyField(blank=True, related_name='banned_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
