# Generated by Django 5.1.7 on 2025-04-15 02:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_post_ban_admin_post_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hidden_posts',
            field=models.ManyToManyField(related_name='hidden_users', to='pages.post'),
        ),
        migrations.CreateModel(
            name='ReportedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_reason', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('In Progress', 'In Progress'), ('Addressed', 'Addressed')], default='Reported')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='reported_posts',
            field=models.ManyToManyField(related_name='reported_users', through='pages.ReportedPost', to='pages.post'),
        ),
    ]
