# Generated by Django 5.1.7 on 2025-04-14 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_post_tagged_users_alter_post_owner_taggeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(related_name='tagged_posts', through='pages.TaggedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
