# Generated by Django 5.1.7 on 2025-04-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_post_tagged_users'),
        ('pages', '0021_user_hidden_posts_reportedpost_user_reported_posts'),
    ]

    operations = [
    ]
