# Generated by Django 5.1.6 on 2025-04-15 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_merge_20250415_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged_users',
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
