# Generated by Django 5.1.6 on 2025-04-15 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_post_tagged_users_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(related_name='tagged_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
