# Generated by Django 5.1.6 on 2025-04-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('gig_type', models.CharField(choices=[('oneTime', 'One-time Gig'), ('recurring', 'Recurring Gig'), ('longTerm', 'Long-term Gig')], max_length=10)),
                ('event_description', models.TextField()),
                ('payment_type', models.CharField(choices=[('Fixed amount', 'Fixed amount'), ('Hourly rate', 'Hourly rate')], max_length=15)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('recurring_pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='pages.business')),
                ('genres', models.ManyToManyField(related_name='job_listings', to='pages.genre')),
                ('instruments', models.ManyToManyField(related_name='job_listings', to='pages.instrument')),
            ],
        ),
    ]
