# Generated by Django 5.1.6 on 2025-05-01 19:01

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_joblisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=35)),
                ('last_name', models.TextField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Enter a valid US phone number (e.g., '+1 123-456-7890', '(123) 456-7890', or '1234567890').", regex='^\\+?1?\\s?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')])),
                ('alt_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]), default=list, size=10, verbose_name='S3 file keys')),
                ('status', models.CharField(choices=[('In-Progress', 'In-Progress'), ('Submitted', 'Submitted'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='musician', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.joblisting')),
            ],
        ),
    ]
