# Generated by Django 5.1.7 on 2025-05-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_message'),
        ('pages', '0029_experience'),
    ]

    operations = [
    ]
