name: Django CI

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: ${{ secrets.DJANGO_ENV }}
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CHROMIUM_BROWSER_PATH: "/usr/bin/chromium-browser"
      CHROME_DRIVER_PATH: '/usr/bin/chromedriver'
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
    - name: Install Backend Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
        npm audit fix
        npm run build

    - name: Run Docker Compose
      run: docker compose up -d

    - name: Wait for Services to be Ready
      run: |
        cd frontend
        npm run dev &
        for i in {1..300}; do
          if curl -s http://localhost:3000 > /dev/null; then
            echo "Services are up!"
            break
          fi
          echo "Waiting for frontend..."
          sleep 2
        done
        
        cd ..
        cd backend
        python manage.py runserver &
        for i in {1..300}; do
          if curl -s http://localhost:8000 > /dev/null; then
            echo "Services are up!"
            break
          fi
          echo "Waiting for backend..."
          sleep 2
        done

    - name: Run Backend Tests
      run: |
        cd backend
        pytest
        behave test/features/
    - name: Run Frontend Tests
      run: |
        cd frontend
        npm run test
        