name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BACKEND_API: ${{ secrets.BACKEND_API }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      DJANGO_ENV: ${{ secrets.DJANGO_ENV }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      FRONTEND_API: ${{ secrets.FRONTEND_API }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_FRONTEND_API: ${{ secrets.NEXT_PUBLIC_FRONTEND_API }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
        npm audit fix
    - name: Install Backend Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Browser Dependencies (Chromium, ChromeDriver, XVFB, and Libraries)
      shell: bash
      run: |
        set -euo pipefail

        # 1) Update & install utilities + Xvfb + common Chrome libs
        sudo apt-get update
        sudo apt-get install -y \
          jq xvfb \
          libnss3 libxi6 libxcursor1 libxcomposite1 libxrandr2 \
          libatk1.0-0 libatk-bridge2.0-0 libcups2

        # 2) Gather every Chromium version from apt
        mapfile -t CHROME_VERSIONS < <(
          apt-cache madison chromium-browser \
            | awk '{print $3}' \
            | sort -u -V
        )

        # 3) Gather every ChromeDriver version from apt
        mapfile -t DRIVER_VERSIONS < <(
          apt-cache madison chromium-chromedriver \
            | awk '{print $3}' \
            | sort -u -V
        )

        # 4) Compute the intersection and pick the newest common version
        COMMON_VERSIONS=($(comm -12 \
          <(printf '%s\n' "${CHROME_VERSIONS[@]}") \
          <(printf '%s\n' "${DRIVER_VERSIONS[@]}") \
        ))
        TARGET_VERSION="${COMMON_VERSIONS[-1]}"
        echo "Latest common Chromium/ChromeDriver version: $TARGET_VERSION"

        # 5) Pin-install both to that exact version
        echo "Installing chromium-browser and chromium-chromedriver@$TARGET_VERSION"
        sudo apt-get install -y \
          chromium-browser="$TARGET_VERSION" \
          chromium-chromedriver="$TARGET_VERSION"

    - name: Configure AWS Profile for s3
      run: |
        mkdir -p ~/.aws
        # Create the credentials file with default credentials
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        # Create the config file with the role configuration
        echo "[profile ${{ secrets.AWS_PROFILE }}]" > ~/.aws/config
        echo "role_arn = arn:aws:iam::314146328946:role/${{ secrets.AWS_PROFILE }}" >> ~/.aws/config
        echo "source_profile = default" >> ~/.aws/config
        echo "region = ${{ secrets.AWS_REGION }}" >> ~/.aws/config
        echo "output = json" >> ~/.aws/config
    - name: Run Frontend Tests
      run: |
        docker compose up -d
        cd frontend
        npm run test
    - name: Run Backend Tests
      run: |
        docker compose up -d
        cd backend
        python manage.py migrate
        pytest
    - name: Run Behave Tests
      run: |
        # Behave needs the frontend and backend running in background to test.
        (cd frontend && npm run dev &)
        
        (cd backend && sudo systemctl start postgresql && python3 manage.py runserver &)
        export CHROME_OPTIONS="--headless --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222"
        echo "Waiting for servers to be fully up..."
        sleep 15
        (cd backend && xvfb-run behave test/features)
